In [1]:
import numpy as np

In [15]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])

array2 = np.linalg.inv(array1)
print(array2)

array3 = array1 @ array2
print(array3)

[[ 0.19230769 -0.30769231]
 [-0.11538462  0.38461538]]
[[1. 0.]
 [0. 1.]]


(2, 2)

In [12]:
#2. 運用上列array計算特徵值、特徵向量?
w, v = np.linalg.eig(array1)
print("The eigenvalue is:", w)
print("The eigenvector is:", v)

The eigenvalue is: [13.  2.]
The eigenvector is: [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


array([13.,  2.])

In [16]:
#3. 運用上列array計算SVD?
u, s, vh = np.linalg.svd(array1)

print(u)
print(s)
print(vh)

[[-0.91663818 -0.39971796]
 [-0.39971796  0.91663818]]
[13.94721714  1.86417116]
[[-0.74319741 -0.6690722 ]
 [-0.6690722   0.74319741]]
